ALTER TABLE "Shop" ADD COLUMN "coverImageFrame" TEXT NOT NULL DEFAULT 'wide';
ALTER TABLE "Shop" ADD COLUMN "coverImageFit" TEXT NOT NULL DEFAULT 'cover';
ALTER TABLE "Shop" ADD COLUMN "coverImagePosition" TEXT NOT NULL DEFAULT 'center';
ALTER TABLE "Shop" ADD COLUMN "coverImageZoom" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Shop" ADD COLUMN "coverImagePositionX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Shop" ADD COLUMN "coverImagePositionY" INTEGER NOT NULL DEFAULT 50;
